### PR TITLE
Upgrade to version 2.2.3

### PR DESCRIPTION
**Pull request by stuartcampbell**
Just a version upgrade.

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
It looks like we might need to add `protobuf` as a requirement. I'm not sure if other environment variables then need to be set. If you could try to figure this out locally that would be great. If not, I can take a look once I have some free time.

**Comment by stuartcampbell** [comment]
No problem, I'll have a look.  I've got it building locally on linux.  I'm not sure of the 'correct' conda-forge way of doing this.  Any comments would be greatly appreciated.  I suspect I will need to do something slightly different for the Windows build ?  I am presuming that the paths are not the unix `include`, `lib` and `bin`.

**Comment by stuartcampbell** [comment]
@synapticarbors Hi, just wanted to see if this was ok to merge ? If there's any other changes needed then please let me know.

**Comment by stuartcampbell** [comment]
Thank you

**Pull request merged**
