### PR TITLE
Bump version to 8.0.11

### PR DESCRIPTION
**Pull request by nehaljwani**

### CODE REVIEW

**Comment by nehaljwani** [comment]
@conda-forge-admin, please rerender

**Comment by nehaljwani** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by nehaljwani** [comment]
I think in order for the Windows build to pass, we need to first fix https://github.com/conda-forge/libprotobuf-feedstock/pull/2 and then also use a libprotobuf which fixes https://github.com/google/protobuf/issues/4717

**Comment by synapticarbors** [comment]
Closed by #10

**Pull request closed without merging**
